---
title: "What’s in this guide? Why host a Jumpstart Program? "
---

The impetus for this program stemmed from observations we made in our Libraries as well as what we were hearing from our colleagues at peer institutions. Simply put: recruiting for technical positions in libraries is difficult. LIS students have differential opportunities to build the skills they need to be successful in these roles, and we wanted to help fill the gap. 

Even though our university does not offer a graduate degree in Library or Information Science, we recognized that our library system is uniquely positioned to offer a program like this. In not having a graduate program in LIS, we have the freedom and bandwidth to provide supplemental opportunities to enhance students’ education. Our Libraries are well regarded for their unique spaces and services, their commitment to emerging technology, and their spirit of experimentation and innovation. Offering a program such as this is one way for us to invest in the future of library school graduates. 

We believe that there is value in building a network of similar programs across organizations. This guide details our process for conceptualizing, planning, hosting, and assessing this program in the hopes that this information will be useful for others looking to begin similar programs at their institutions. 

Additionally, we anticipate that the framework presented in this document could be adapted to create similar programs for other audiences (a Jumpstart Program for current librarians and archivists hoping to build their tech skills, for example). 


> <i>Tip: Look for these highlighted tips at the end of each section for the quick summary version.</i> 

[Next >> Process Overview](https://cullerth.github.io/jumpstart_website/timeline.html)