---
title: 'Step 5: Program Lead-up'
---

While transitioning to an online program did have its affordances, it also required more direct attention to be paid to certain areas. This included the type and frequency of communications we engaged in with participants leading up to the program, namely the creation of thorough documentation and a number of pre-program surveys to help determine participants’ needs. 

## Pre-program communications ##
In order to take stock of participants accessibility requirements and technology set-ups, we sent out a pre-program survey to gather the following information: 

<i>“This survey is intended to gather information about your work environment and tech set up, your baseline skills and knowledge heading into the program, as well as what accessibility accommodations you may require. We acknowledge that some of you will be beginning from a place of no previous technical experience, and that others of you may have some working knowledge. Both starting points are valid. Knowing where everyone stands will allow us to properly prepare and tailor content. Please complete this survey by Wed, June 18th. It should take roughly 10 minutes to complete. Thank you for your participation” </i>

- Equipment: 
  + Do you have access to a laptop or desktop computer to work with the week of the program? (*Please note that for the purposes of the program, using an iPad or tablet will not suffice. If you have questions or concerns about the device you will be using for the week, reach out to us! We will work with you to identify accommodations.*)
  + Do you have permissions to install new software on this computer?
  + Do you have a reliable internet connection at the location you will be joining us from? (*If not, let us know and we can discuss potentially shipping you a hotspot or work to find some other solution.*) 
  + What operating system & version will you be using? (e.g. MacOS Mojave, Windows 10, Ubuntu Linux, etc.) (*If you are unsure, that's okay! Note that here and we will reach out to you to help you figure it out.*) 
  + Please list any technical courses you have completed (through your program or otherwise) as well as any intensive workshops and/or tech-related bootcamps you may have taken part in here:
  + Please indicate which tools you have some experience working with. (check all that apply) [the command line/terminal; a text editor; python; git/github; html; css; a web framework, such as flask or django; I really haven't used any of these things before. (and that's ok!)]        
  + If you have a GitHub username, please provide it below: (*This will help us plan our Git & GitHub workshop. If you don't have a GitHub username, we'll help you set one up later.*)
  + What's your experience with programming? Choose one of the following levels: 
    * Level 1 - Totally New to Programming: You might have done a little bit with HTML or CSS, but not necessarily; You're unfamiliar with terms like methods, arrays, lists, hashes, or dictionaries.
    * Level 2 - Somewhat New to Programming: You might have done an online programming tutorial or two, but don't have a lot of experience with programming; You know what an array is
    * Level 3 - Some Programming Experience: You have some experience with a programming language and version control; You understand general programming concepts, like collections and scope, but aren't a power user
    * Level 4 - Ready for the Next Challenge: You're comfortable with the terminal and are proficient in at least one programming language; You want to problem-solve instead of copying others' code
  + What is your familiarity with machine learning? 
    * I have no clue what machine learning is.
    * I have heard of machine learning before and kind of understand what it's about, but would have trouble describing it to someone else.
    * I have a basic conceptual understanding of machine learning, but don't know how it works on a technical level.
    * I understand how machine learning works on a conceptual and a technical level.

- Accessibility & Accomodations:    
*In compliance with the Americans with Disabilities Act, NC State University Libraries will gladly honor requests for reasonable accommodations. Please note your accommodation requests below or send them directly to Tori Culler (tculler@ncsu.edu) by Monday, July 12th, 2021. All sessions will feature automated captioning. We are happy to provide live captioning by a professional captioner upon request. Recordings and transcripts for most sessions will be available to participants for a period of time after the Jumpstart Program concludes.* 
  + Do you require any accessibility accommodations for the week of the program? (*We can offer, for example, alternative formats for recorded videos, additional break time, etc.*)
  + Do you have access to any assistive technology you might need for the week? (*The NC State University Libraries is committed to providing access to collections, services, and spaces for all library users. When we use the phrase "assistive technology", we are referring specifically to technologies used to facilitate access to materials for participants with a variety of vision, hearing, and/or mobility-related disabilities. Outside of Zoom (which will be live captioned), we'll provide you with materials in these formats: Google Docs, videos on Vimeo (captioned), PDFs, and downloadable code files on Github. At your request, we can offer things like JAWS screen-reading software to facilitate your access to those materials.*)
- General questions, comments, concerns:
  + Is there anything else you would like us to know? Do you have anything to add concerning your answers to the above questions? 
  
We were able to use the information gleaned from this survey to plan our technical workshops around folks experiences and skill levels. In 2020, information obtained in this survey also prompted us to begin working on the process of securing live captioning and inserting more break time into our schedule. For live captioning, we worked with [CaptionSync](https://www.automaticsync.com/captionsync/) to secure services. In 2021, we learned from this survey that we would need to ship a participant a loaner laptop. 

In addition to the pre-program tech & accommodations survey, we also sent out a pre-program knowledge & attitudes survey as part of our assessment plan (see Step 6: Assessment, for more information). 

A couple weeks before the program, we gave participants access to a shared Google Drive folderthat we pitched as their one-stop-shop for all things Jumpstart, including all pre-program support materials such as the program schedule with Zoom links and the code of conduct, program support materials (such as workshop slides and glossaries), as well as all post-program support materials (including guides for continued learning, etc.). We outlined the folder's contents in a README document. 

> Tip: Frequent and clear communication with participants leading up to the program is key to a successful delivery. Seek input from participants about what their technology and access needs are very early on to ensure that you have adequate time to meet them. Consider creating a comprehensive information packet/shared drive that includes all needed information to share with participants beforehand. 

## Install-fest ##

One challenge that often occurs with technical workshops is making sure that participants have the software that they need installed and configured. This is often even more of a challenge when participants use different versions and flavors of operating systems (such as Mac vs Windows vs Linux, and different versions of each one). Using tools such as [Google Colaboratory](https://colab.research.google.com/) helps with this problem, as you can do the coding live in a browser, and not require users to install anything on their own machines. We felt, however, that participants would benefit from learning how to set up a programming environment on their own machines they could continue to use after the end of the Jumpstart program. This would also help us ensure that all requirements were installed, tested, and working before the week of the program. To this end, we offered what we called “Install-fest”.

A few weeks before the program, we reached out to participants with [instructions](https://docs.google.com/document/d/1UBtvsXuAiqBGFWCQNV4__28cE5toGxpCYYr0HcR0cR8/edit) on how to get a programming environment setup on their machines, and how to install dependencies for each of the workshops we offered. We also asked them to schedule a one-hour one-on-one session with us, where we could either run through the instructions together, answer specific questions they had, or just verify their environments were set up properly and working. We had volunteers to help with the one-on-one sessions that were familiar with the operating system that the participant used.

This approach ended up working out well -- most of the issues that we ran into during the hands-on workshops were not related to the environment set up of participants. It was also a good chance to begin to develop a rapport with participants and help them get comfortable with sharing their screens and troubleshooting issues together. We were able to offer participants one-on-one support because our cohort size was fairly small. If we had a larger cohort size, we could have considered having small group support sessions instead of one-on-one.

> Tip: Create a plan to make sure participants are as prepared as they can be in advance of any technical workshops you plan to offer so that they can focus on the content of the workshop rather than on issues with their computing environments.

[Next >> Step 6: Program Delivery](https://ncsu-libraries.github.io/jumpstart-framework/delivery.html)

<br>

Last updated on `r format(Sys.time(), '%B %d, %Y.')`