---
title: "Further Reading/Suggested Resources"
---

## Our informal literature review bibliography: 
Bertot, John Carlo, Lindsay C. Sarin, and Johnna Percell. "Re-envisioning the MLS: Findings, issues, and considerations." University of Maryland, College Park, College of Information Studies, 2015. http://mls.umd.edu/wp-content/uploads/2015/08/ReEnvisioningFinalReport.pdf

Bourg, Chris. “The Unbearable Whiteness of Librarianship.” Feral Librarian (blog), March 3, 2014. https://chrisbourg.wordpress.com/2014/03/03/the-unbearable-whiteness-of-librarianship.

Carson, Pamela. "Re-Framing Librarians' Identities and Assumptions Around IT." The Journal of Academic Librarianship 40, no. 3-4 (2014): 405-407. https://doi.org/doi:10.1016/j.acalib.2014.03.011 

Cruz, Justin de la, and Joshua Hogan. "“Hello, World!”: Starting a Coding Group for Librarians." Public Services Quarterly 12, no. 3 (2016): 249-256. https://doi.org/10.1080/15228959.2016.1197082 

Bosque, Darcy Del, and Cory Lampert. "A chance of storms: New librarians navigating technology tempests." Technical Services Quarterly 26, no. 4 (2009): 261-286. http://dx.doi.org/10.1080/07317130802678878

Emanuel, Jenny. "Digital native academic librarians, technology skills, and their relationship with technology." Information Technology and Libraries 32, no. 3 (2013): 20-33. https://doi.org/10.6017/ital.v32i3.3811 

Fife, Dustin, and Mary Naylor Stephens. "Swiss Army Degree: Library and Information Science." In Re-envisioning the MLS: Perspectives on the Future of Library and Information Science Education. Emerald Publishing Limited, 2018.

Garcia, Sergei. “My Journey to Becoming a Web Developer from Scratch without a CS Degree (and What I Learned from It).” Medium, May 11, 2018. https://medium.com/free-code-camp/my-journey-to-becoming-a-web-developer-from-scratch-without-a-cs-degree-2-years-later-and-what-i-4a7fd2ff5503 

Gonzales, Brighid M. "Computer Programming for Librarians: A Study of Job Postings for Library Technologists." Journal of Web Librarianship 13, no. 1 (2019): 20-36. https://doi.org/10.1080/19322909.2018.1534635 

Hathcock, April. "White librarianship in blackface: Diversity initiatives in LIS." In the Library with the Lead Pipe (blog), Oct. 7, 2015. http://www.inthelibrarywiththeleadpipe.org/2015/lis-diversity/ 

Johnson, Maggie and Max Senges. "Learning to be a Programmer in a Complex Organization: A Case Study on practice‐based Learning during the Onboarding Process at Google." The Journal of Workplace Learning 22, no. 3 (2010): 180-194. http://dx.doi.org/10.1108/13665621011028620  

Maceli, Monica. "Creating Tomorrow's Technologists: Contrasting Information Technology Curriculum in North American Library and Information Science Graduate Programs Against Code4lib Job Listings." Journal of Education for Library and Information Science 56, no. 3 (2015): 198. https://www.jstor.org/stable/90015186

Maceli, Monica. “What Technology Skills Do Developers Need? A Text Analysis of Job Listings in Library and Information Science (LIS) from Jobs.Code4lib.Org.” Information Technology and Libraries 34, no. 3 (2015): 8–21. https://doi.org/10.6017/ital.v34i3.5893.

Maceli, Monica, and John J. Burke. “Technology Skills in the Workplace: Information Professionals’ Current Use and Future Aspirations.” Information Technology and Libraries 35 no. 4 (2016): 35–62. https://doi.org/10.6017/ital.v35i4.9540.

Maceli, Monica. "Tech-savvy librarian versus (library) technologist: understanding the future role of librarians in technology practice." In Re-envisioning the MLS: Perspectives on the Future of Library and Information Science Education. Emerald Publishing Limited, 2018. https://doi.org/10.1108/S0065-28302018000044B009.

Pronschinske, Mitch.  “Bootcamps Won’t Make You a Coder. Here’s What Will.” TechBeacon, 2016. https://techbeacon.com/app-dev-testing/bootcamps-wont-make-you-coder-heres-what-will 

Riley-Huff, DA and JM Rholes. "Librarians and Technology Skill Acquisition: Issues and Perspectives." Information Technology and Libraries 30, no. 3 (2011): 129-140. https://doi.org/10.6017/ital.v30i3.1770 

Scripps-Hoekstra, Lindy, Megan Carroll, and Theresa Fotis. "Technology Competency Requirements of ALA-Accredited Library Science Programs: An Updated Analysis." Journal of Education for Library and Information Science 55, no. 1 (2014): 40-54. https://www.jstor.org/stable/43686966 

Singh, Vandana and Mehra, Bharat. “Strengths and weaknesses of the information technology curriculum in library and information science graduate programs.” Journal of Librarianship and Information Science 45, no. 3(2013): 219–231. https://doi.org/10.1177/0961000612448206  

Wusteman, Judith. "Introducing web components into the LIS graduate curriculum." Information and Learning Science (2017). https://doi.org/10.1108/ILS-08-2017-0084.

Yelton, Andromeda. Coding for librarians: learning by example. American Library Association, 2015.

“Why Would a Librarian Learn to Code?” 2016. Code and the Librarian (blog). January 24, 2016. https://codeandthelibrarian.wordpress.com/2016/01/24/why-would-a-librarian-learn-to-code/ 
